/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_forms;

import pack_forms.frmDatosViaje;
import pack_clases.Viaje;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author ALFONSO
 */
public class frmIngresarViaje extends javax.swing.JInternalFrame {
private void bloquear(){
        for(Component a:  txtvuelta.getComponents()){
            a.setEnabled(false);
        }
    }
    private void desbloquear(){
        for(Component b: txtvuelta.getComponents()){
            b.setEnabled(true);
        }
    }
    private void desb_bloq(){
        if(rbida.isSelected()){
            bloquear();
        }else{
            desbloquear();
        }
        
    }
     private void Listar_cabina(){
        cmbcabina.addItem("--Seleccione--");
        cmbcabina.addItem("Economy");
        cmbcabina.addItem("Premiun Economy");
        cmbcabina.addItem("Premiun Business");
        
    }
     

     
     public static LinkedList contenedor=new LinkedList();
     public int buscar;
     
     

    public frmIngresarViaje() {
        initComponents();
        Listar_cabina();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtorigen = new javax.swing.JTextField();
        txtdestino = new javax.swing.JTextField();
        rbida = new javax.swing.JRadioButton();
        rbidayvuelta = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnumpasajeros = new javax.swing.JTextField();
        cmbcabina = new javax.swing.JComboBox<>();
        btnagregar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        txtida = new javax.swing.JTextField();
        txtvuelta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 440));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("ORIGEN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("DESTINO");

        txtorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorigenActionPerformed(evt);
            }
        });
        txtorigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtorigenKeyTyped(evt);
            }
        });

        txtdestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdestinoKeyTyped(evt);
            }
        });

        grupo.add(rbida);
        rbida.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbida.setText("Solo Ida");
        rbida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbidaActionPerformed(evt);
            }
        });

        grupo.add(rbidayvuelta);
        rbidayvuelta.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbidayvuelta.setText("Ida y Vuelta");
        rbidayvuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbidayvueltaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("IDA");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("VUELTA");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("N° PASAJEROS");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("CABINA");

        btnagregar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnagregar.setText("AGREGAR VIAJE");
        btnagregar.setToolTipText("");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmostrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnmostrar.setText("MOSTRAR TABLA");
        btnmostrar.setToolTipText("");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        txtida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidaKeyTyped(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack_imagenes/images.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbida)
                        .addGap(18, 18, 18)
                        .addComponent(rbidayvuelta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumpasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagregar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtvuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cmbcabina, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnmostrar)
                                .addGap(3, 3, 3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbida)
                            .addComponent(rbidayvuelta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumpasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbcabina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmostrar)
                            .addComponent(btnagregar))
                        .addGap(140, 140, 140))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorigenActionPerformed

    private void txtorigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorigenKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Escribe Nombres de Paises y/o Capitales");
        }
        if(txtorigen.getText().length()>=20){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtorigenKeyTyped

    private void txtdestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdestinoKeyTyped
        char val=evt.getKeyChar();
        if(Character.isDigit(val)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Escribir nombres de Ciudades");

        }
        if(txtdestino.getText().length()>=20){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtdestinoKeyTyped

    private void rbidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbidaActionPerformed
        
        if(rbida.isSelected()){
            txtvuelta.setEnabled(false);
        }
    }//GEN-LAST:event_rbidaActionPerformed

    private void rbidayvueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbidayvueltaActionPerformed
        if(rbidayvuelta.isSelected()){
            txtvuelta.setEnabled(true);
        }
            
    }//GEN-LAST:event_rbidayvueltaActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
//        int year=dcida.getCalendar().get(Calendar.YEAR);
//        int mes=dcida.getCalendar().get(Calendar.MONTH);
//        int dia=dcida.getCalendar().get(Calendar.DAY_OF_MONTH);
//
//        String fechaida=""+year+"-"+mes+"-"+dia;
//        int anio=dcvuelta.getCalendar().get(Calendar.YEAR);
//        int month=dcvuelta.getCalendar().get(Calendar.MONTH);
//        int day=dcvuelta.getCalendar().get(Calendar.DAY_OF_MONTH);
//        String fechavuelta=""+anio+"-"+month+"-"+day;

        String fechaida=txtida.getText();
        String fechavuelta=txtvuelta.getText();
        String or=txtorigen.getText();
        String des=txtdestino.getText();
        String nu_pas=txtnumpasajeros.getText();
        String cab=cmbcabina.getSelectedItem().toString();
        Viaje vu=new Viaje(or, des, nu_pas, cab, fechaida, fechavuelta);
        contenedor.add(vu);
        //Limpiando campos despues de guardar
        txtorigen.setText(null);
        txtdestino.setText(null);
        txtida.setText(null);
        txtvuelta.setText(null);
        txtnumpasajeros.setText(null);
        grupo.clearSelection();
        cmbcabina.setSelectedIndex(0);     
//        try {
//            con= DriverManager.getConnection("jdbc:sqlserver://DESKTOP-V1NHLNM:1433;databaseName=Base_aerolinea","BaseSQL","123");
//
//            Statement stmt= con.createStatement();
//            stmt.executeUpdate("INSERT INTO vuelos VALUES('"+txtorigen.getText()+"','"+txtdestino.getText()+"',"
//                + "'"+fechaida+"','"+fechavuelta+"','"+txtnumpasajeros.getText()+"','"+cmbcabina.getSelectedItem()+"')");
//
//        } catch (SQLException ex) {
//            Logger.getLogger(IngresarVuelo.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "No se puede conectar con la base de Datos");
//        }
//        JOptionPane.showMessageDialog(null, "Viaje Registrado Exitosamente");
//        limpiar_pantalla();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        frmDatosViaje dat=new frmDatosViaje();
        dat.setVisible(true);
        
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void txtidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidaKeyTyped
        char val=evt.getKeyChar();
        if(Character.isLetter(val)){
            getToolkit().beep();
            evt.consume();
            

        }
    }//GEN-LAST:event_txtidaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JComboBox<String> cmbcabina;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbida;
    private javax.swing.JRadioButton rbidayvuelta;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtida;
    private javax.swing.JTextField txtnumpasajeros;
    private javax.swing.JTextField txtorigen;
    private javax.swing.JTextField txtvuelta;
    // End of variables declaration//GEN-END:variables
}
